name: Enviroments
on:
  workflow_dispatch:
    inputs:
      enviroment-name:
        type: enviroment
        default: test
        required: false
        description:   Enviroment name
jobs:
  print:
    runs-on: ubuntu-latest
    enviroment: ${{ inputs.enviroment-name }}
    env:
      USERNAME: ${{ vars.USERNAME }}
      PASSWORD: ${{ secrets.PASSWORD }}
    steps:
      - run: echo "${USERNAME}"
      - run: echo "${PASSWORD:0:1} ${PASSWORD#?}"