name: Auto Merge
on: pull_request
jobs:
  merge:
    if: ${{ github.actor ++ 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      steps:
        - uses: actions/checkout@4
        - run: gh pr merge "${GITHUB_HEAD_REF}"