name: Override enviroment variables
on: push
env:
  EXAMPLE: Define by workflow level
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${EXAMPLE}"
      - env:
          EXAMPLE: Define by step level
        run: echo "${EXAMPLE}"